/**
 * Standardized error codes for the extension.
 * Grouped by category for easy identification.
 */
export enum ErrorCode {
  // General
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  TIMEOUT = 'TIMEOUT',
  ABORTED = 'ABORTED',

  // AI Provider
  AI_API_ERROR = 'AI_API_ERROR',
  AI_RATE_LIMIT = 'AI_RATE_LIMIT',
  AI_INVALID_KEY = 'AI_INVALID_KEY',
  AI_QUOTA_EXCEEDED = 'AI_QUOTA_EXCEEDED',
  AI_MODEL_NOT_FOUND = 'AI_MODEL_NOT_FOUND',
  AI_PARSE_ERROR = 'AI_PARSE_ERROR',

  // Browser
  TAB_NOT_FOUND = 'TAB_NOT_FOUND',
  TAB_CLOSED = 'TAB_CLOSED',
  TAB_PERMISSION_DENIED = 'TAB_PERMISSION_DENIED',
  CONTENT_SCRIPT_NOT_READY = 'CONTENT_SCRIPT_NOT_READY',
  CONTENT_SCRIPT_INJECTION_FAILED = 'CONTENT_SCRIPT_INJECTION_FAILED',

  // DOM
  ELEMENT_NOT_FOUND = 'ELEMENT_NOT_FOUND',
  ELEMENT_NOT_VISIBLE = 'ELEMENT_NOT_VISIBLE',
  ELEMENT_NOT_INTERACTIVE = 'ELEMENT_NOT_INTERACTIVE',
  ELEMENT_DETACHED = 'ELEMENT_DETACHED',
  MULTIPLE_ELEMENTS_FOUND = 'MULTIPLE_ELEMENTS_FOUND',

  // Action
  ACTION_INVALID = 'ACTION_INVALID',
  ACTION_FAILED = 'ACTION_FAILED',
  ACTION_BLOCKED = 'ACTION_BLOCKED',
  NAVIGATION_FAILED = 'NAVIGATION_FAILED',

  // Session
  SESSION_NOT_FOUND = 'SESSION_NOT_FOUND',
  SESSION_EXPIRED = 'SESSION_EXPIRED',
  SESSION_LIMIT_REACHED = 'SESSION_LIMIT_REACHED',

  // Storage
  STORAGE_QUOTA_EXCEEDED = 'STORAGE_QUOTA_EXCEEDED',
  STORAGE_READ_ERROR = 'STORAGE_READ_ERROR',
  STORAGE_WRITE_ERROR = 'STORAGE_WRITE_ERROR',

  // Security
  DOMAIN_BLOCKED = 'DOMAIN_BLOCKED',
  SCRIPT_BLOCKED = 'SCRIPT_BLOCKED',
  SENSITIVE_DATA_DETECTED = 'SENSITIVE_DATA_DETECTED',
}
