import type { ActionType } from '@shared/types/actions';

export const SHIPPED_ACTION_TYPES = [
  'navigate',
  'goBack',
  'goForward',
  'reload',
  'click',
  'doubleClick',
  'rightClick',
  'hover',
  'focus',
  'fill',
  'type',
  'clear',
  'uploadFile',
  'select',
  'check',
  'uncheck',
  'press',
  'hotkey',
  'scroll',
  'scrollIntoView',
  'wait',
  'waitForElement',
  'waitForNavigation',
  'waitForNetwork',
  'extract',
  'extractAll',
  'screenshot',
  'fullPageScreenshot',
  'newTab',
  'closeTab',
  'switchTab',
  'evaluate',
  'emulateDevice',
  'interceptNetwork',
  'mockResponse',
  'mockGeolocation',
  'savePdf',
] as const satisfies readonly ActionType[];

